language: node_js
sudo: false
node_js:
  - "0.8"
  - "0.10"
  - "4.9"
  - "6.17"
  - "8.16"
  - "10.16"
  - "12.6"
before_install:
  # Setup npm
  - "test $TRAVIS_NODE_VERSION != '0.8' || npm install -g npm@1.2.8000"
  - "npm config set shrinkwrap false"
  # Setup Node.js version-specific dependencies
  - |
    # nyc for coverage
    # - remove for Node.js < 6
    if [[ "$(cut -d. -f1 <<< "$TRAVIS_NODE_VERSION")" -lt 6 ]]; then
      npm rm --silent --save-dev nyc
    fi
script:
  # Run test script
  - |
    if npm -ps ls nyc | grep -q nyc; then
      npm run test-cov
    else
      npm test
    fi
after_script:
  - |
    # Upload coverage to coveralls if exists
    if [[ -d .nyc_output ]]; then
      npm install --save-dev coveralls@2
      nyc report --reporter=text-lcov | coveralls
    fi
