language: node_js
sudo: false
node_js:
  - "0.10"
  - "4.9"
  - "6.17"
  - "8.16"
  - "10.15"
after_script:
  - "test -e ./coverage/lcov.info && npm install coveralls@2 && coveralls < ./coverage/lcov.info"
