environment:
  matrix:
    - nodejs_version: "0.8"
    - nodejs_version: "0.10"
    - nodejs_version: "4.9"
    - nodejs_version: "6.17"
    - nodejs_version: "8.16"
    - nodejs_version: "10.16"
install:
  # Install Node.js
  - ps: >-
      try { Install-Product node $env:nodejs_version -ErrorAction Stop }
      catch { Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) }
  # Setup npm
  - for /f "tokens=*" %%g in ('where npm') do (set npm_prefix=%%~dpg)
  - if "%nodejs_version%" equ "0.8" npm config set strict-ssl false
  - if "%nodejs_version%" equ "0.8" npm install -g --prefix "%npm_prefix:~0,-1%" npm@1.2.8000
  - npm config set shrinkwrap false
  # Install Node.js modules
  - npm install
build: off
test_script:
  # Output version data
  - ps: |
      node --version
      npm --version
  # Run test script
  - npm test
version: "{build}"
